language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: 68cb2b19bd0280d6cd462dc4eca6d207db89f0a6 # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: master